---

- hosts: all
  become: yes
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present

    - name: create index.html 
      copy:
        dest: /var/www/html/index.html
        content: "Welcome to my website"    
    
    - name: Ensure Nginx engine is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes    
